//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dke.file
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateEnter { get; set; }
        public Nullable<System.DateTime> DateExit { get; set; }
        public int RoomId { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
