//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dke.file
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id { get; set; }
        public string Task { get; set; }
        public bool Completed { get; set; }
        public int EmployeeId { get; set; }
        public int RoomId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
