//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dke.file
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string ULogin { get; set; }
        public string UPassword { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> LastLoginAttempt { get; set; }
        public Nullable<System.DateTime> LastSuccessfulLogin { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
